/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2016-03-29 03:45:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class imgRecognition_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html SYSTEM \"about:legacy-compat\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset=\"utf-8\"/>\r\n");
      out.write("      <meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\"/>\r\n");
      out.write("      <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\r\n");
      out.write("      <meta content=\"suDeBu3cQ5JEfYn92UdyZqkDPVCRI3QFK4dbV1tzUNk\" name=\"google-site-verification\"/>\r\n");
      out.write("      <link href=\"http://webcore.unm.edu/v1/images/unm.ico\" rel=\"shortcut icon\"/>\r\n");
      out.write("      <link href=\"http://webcore.unm.edu/v2/css/unm-styles.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("      <!-- bootstrap-carousal-->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link href=\"css/style1.css\" rel=\"stylesheet\">\r\n");
      out.write("   \r\n");
      out.write("   </head>\r\n");
      out.write("   <body id=\"home\">\r\n");
      out.write("\r\n");
      out.write("   <div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"navbar navbar-unm\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               <a class=\"navbar-brand\" href=\"http://www.unm.edu\">The University of New Mexico</a><!-- search form -->\r\n");
      out.write("               \r\n");
      out.write("               <!-- end search form -->\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("         <div id=\"upper\">\r\n");
      out.write("           <div class=\"container\">\r\n");
      out.write("            <br />\r\n");
      out.write("            <br />\r\n");
      out.write("            <div class=\"jumbotron\">\r\n");
      out.write("            <h2 > UNM- Crowd Learning</h2>\r\n");
      out.write("\r\n");
      out.write("   <br />CROWD LEARNING\r\n");
      out.write("   <br />\r\n");
      out.write("This Prototype contribution has the potential to advance scientific discovery while promoting\r\n");
      out.write("teaching, training, and learning. In particular, simple physics and chemistry crowdsourcing tasks will be\r\n");
      out.write("released to high schools as games and as educational exercises for students. It is expected that by interacting\r\n");
      out.write("with these problems, young students will be drawn to STEM fields.\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <form class=\"form-signin\" action=\"/crowdcs/imgreco.jsp\">\r\n");
      out.write("        <h2 class=\"form-signin-heading\">Please sign in</h2>\r\n");
      out.write("        <div class=\"radio\">\r\n");
      out.write("  <label><input type=\"radio\" name=\"optradio\">Users</label>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"radio\">\r\n");
      out.write("  <label><input type=\"radio\" name=\"optradio\">Host</label>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"inputEmail\" class=\"sr-only\">Email address</label>\r\n");
      out.write("        <input type=\"email\" id=\"inputEmail\" class=\"form-control\" placeholder=\"Email address\" required autofocus>\r\n");
      out.write("        <label for=\"inputPassword\" class=\"sr-only\">Password</label>\r\n");
      out.write("        <input type=\"password\" id=\"inputPassword\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"checkbox\">\r\n");
      out.write("          <label>\r\n");
      out.write("            <input type=\"checkbox\" value=\"remember-me\"> Remember me\r\n");
      out.write("          </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">Sign in</button><br />\r\n");
      out.write("        <a href=\"/crowdcs/register.jsp\">New Member Wanna CrowdSource ..Join Us!!!</a>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("  \r\n");
      out.write("   </div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               <hr/>\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-8\">\r\n");
      out.write("                     <p><a href=\"http://www.unm.edu\"><img alt=\"The University of New Mexico\" src=\"https://webcore.unm.edu/v2/images/unm-transparent-white.png\"/></a></p>\r\n");
      out.write("                     <p><small>&#169; The University of New Mexico<br/>\r\n");
      out.write("                        Albuquerque, NM 87131, (505) 277-0111<br/>\r\n");
      out.write("                        New Mexico's Flagship University</small>\r\n");
      out.write("                     </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                     <ul class=\"list-inline\">\r\n");
      out.write("                        <li><a href=\"https://www.facebook.com/universityofnewmexico\" title=\"UNM on Facebook\"><span class=\"fa fa-facebook-square fa-2x\">&#160;</span></a></li>\r\n");
      out.write("                        <li><a href=\"http://instagram.com/uofnm\" title=\"UNM on Instagram\"><span class=\"fa fa-instagram fa-2x\">&#160;</span></a></li>\r\n");
      out.write("                        <li><a href=\"https://twitter.com/unm\" title=\"UNM on Twitter\"><span class=\"fa fa-twitter-square fa-2x\">&#160;</span></a></li>\r\n");
      out.write("                        <li><a href=\"http://uofnm.tumblr.com\" title=\"UNM on Tumblr\"><span class=\"fa fa-tumblr-square fa-2x\">&#160;</span></a></li>\r\n");
      out.write("                        <li><a href=\"http://www.youtube.com/user/unmlive\" title=\"UNM on YouTube\"><span class=\"fa fa-youtube-square fa-2x\">&#160;</span></a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                     <p>more at <a href=\"http://social.unm.edu\" title=\"UNM Social Media Directory &amp; Information\">social.unm.edu</a></p>\r\n");
      out.write("                     <ul class=\"list-inline\" id=\"unm_footer_links\">\r\n");
      out.write("                        <li><a href=\"http://www.unm.edu/accessibility.html\">Accessibility</a></li>\r\n");
      out.write("                        <li><a href=\"http://www.unm.edu/legal.html\">Legal</a></li>\r\n");
      out.write("                        <li><a href=\"http://www.unm.edu/contactunm.html\">Contact UNM</a></li>\r\n");
      out.write("                        <li><a href=\"http://nmhedss2.state.nm.us/Dashboard/index.aspx?ID=21\">New Mexico Higher Education Dashboard</a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write(" \r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
